### PR TITLE
Added plugins/followers, merged plugins/{renick,nickwatcher}

### PR DESCRIPTION
**Pull request by s5i**

### CODE REVIEW

**Comment by StalkR** [comment]
waiting on travis then merging

**Comment by StalkR** [comment]
error: https://travis-ci.org/StalkR/goircbot/builds/69955405

```
plugins/followers/handlers.go:19: syntax error: unexpected name, expecting semicolon or newline or }
plugins/followers/handlers.go:22: non-declaration statement outside function body
plugins/followers/handlers.go:23: syntax error: unexpected }
```

**Comment by StalkR** [comment]
Yeah the line is messed up:
```
}	g.remover
```

**Comment by s5i** [comment]
Sorry bout that! Fixed :)

**Pull request merged**
